/**
 * Open European Public Transit Format (OEPTF)
 * An european standard for public transit.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tristan.marsell@axitera.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.zwei.shibi.model.restyprotobuf

/**
 * This object represents the search body given to the trip search.
 * @param context Context ID
 * @param showTripsBefore Shows trips before the given context, if set to false, it shows trips after the given context.
 */
data class MoreTripsSearch(

    /* Context ID */
    val context: kotlin.String? = null,
    /* Shows trips before the given context, if set to false, it shows trips after the given context. */
    val showTripsBefore: kotlin.Boolean? = null
)
