/**
 * Open European Public Transit Format (OEPTF)
 * An european standard for public transit.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tristan.marsell@axitera.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.zwei.shibi.model.restyprotobuf

/**
 * This object represents the search body given to the trip search.
 * @param originID The ID of your start station/place
 * @param destinationID The ID of your target station/place
 * @param time Datetime where you want to search for
 * @param isArrivalTime Shows if your time is for departure or arrival of your trip.
 */
data class TripSearch(

    /* The ID of your start station/place */
    val originID: kotlin.String? = null,
    /* The ID of your target station/place */
    val destinationID: kotlin.String? = null,
    /* Datetime where you want to search for */
    val time: kotlin.String? = null,
    /* Shows if your time is for departure or arrival of your trip. */
    val isArrivalTime: kotlin.Boolean? = null
)
